galaxy_info:
  author: Srikanth Makineni
  description: certbot ssl cert
  company: itgeeksroom
  
  min_ansible_version: 2.6

  platforms:
    - name: EL
      versions:
        - 7
    - name: Debian
      versions:
        - all

  galaxy_tags: 
    - networking
    - system
    - web
    - certbot
    - acme
    - encryption
    - certificates
    - ssl
    - https
