---
- name: Check if certificate already exists.
  stat:
    path: /etc/certbot/certbot2-public/live/cloud-jen.cisco.com/fullchain.pem
  register: certbot_certificate

- name: Generate new certificate if one doesn't exist.
  command: "{{ certbot_create_command }}"
  when: not certbot_certificate.stat.exists


  