---
# handlers file for certbot_cert

- name: Restart NGINX
  service: name=nginx state=restarted

- name: validate nginx configuration
  command: nginx -t
  changed_when: false

- name: Reload NGINX
  service: name=nginx state=reloaded